### ISSUE TITLE
Code logic issue

### ISSUE THREAD

**Issue by jiere** [sustainable-computing-io/local-dev-cluster#13]
There are still some logic issues need to trace, not so urgent.
In ./kind/common.sh,
1. In check arch part, we announced that we supported three Arch: x86_64, ppc64le, aarch64, however, for KIND [release](https://github.com/kubernetes-sigs/kind/releases), there seems to be only amd64/arm64 supported, so if the runner is ppc64le arch, the server setup will definitely fail.
2. KIND supports darwin/linux/windows $OSTYPE, but we currently only support darwin/linux, do we have plan to support windows here?

In .github/workflows/test.yml,
Current job setup KIND cluster, should we teardown it(this feature is available after #10 merged) after test? I suppose kepler-action does not care about this.

**Comment by jiere** [comment]
Agree with you, we can cleanup ppc64le info currently and ignore windows support.

One more logic issue which I got confused and was missing to mention, still in common.sh:
The current code limits to use KIND version 0.17.0 or 0.19.0, it's OK for me(but I prefer just the latest stable release should be OK).
But why do we need to define such a "_fetch_kind" function to check if the $KIND binary is there?
Since the $KIND_DIR(local-dev-cluster/kind) always exists, only the first time to create the kind cluster, the $KIND binary will be fetch through the curl command.
I am thinking about that why not we just install kind onto the test machine in this way:
check if expected version kind has already been installed:
(1) If yes, do nothing;
(2) If no, install it only once.
The above logic could be implemented in current .github/workflow/test.yaml, since it belongs to the test machine setup job.
And in common.sh itself, we can directly run "kind create xxx" and "kind delete xxx", no need to define specific binary macro as current $KIND.

wdyt @SamYuan1990 ?

**Comment by SamYuan1990** [comment]
> Agree with you, we can cleanup ppc64le info currently and ignore windows support.
> 
> One more logic issue which I got confused and was missing to mention, still in common.sh: The current code limits to use KIND version 0.17.0 or 0.19.0, it's OK for me(but I prefer just the latest stable release should be OK). But why do we need to define such a "_fetch_kind" function to check if the $KIND binary is there? Since the $KIND_DIR(local-dev-cluster/kind) always exists, only the first time to create the kind cluster, the $KIND binary will be fetch through the curl command. I am thinking about that why not we just install kind onto the test machine in this way: check if expected version kind has already been installed: (1) If yes, do nothing; (2) If no, install it only once. The above logic could be implemented in current .github/workflow/test.yaml, since it belongs to the test machine setup job. And in common.sh itself, we can directly run "kind create xxx" and "kind delete xxx", no need to define specific binary macro as current $KIND.
> 
> wdyt @SamYuan1990 ?

maybe not or hold on for a while?
the scripts in this repo is major for CI usage.
The historical is we create a github action as https://github.com/sustainable-computing-io/kepler-action to avoid copy paste k8s cluster set up scripts in CI among kepler repos, next by @marceloamaral 's request, we decoupled this repo from  https://github.com/sustainable-computing-io/kepler-action as a local cluster which supports both CI and local.
Hence I know there lots of things can be enhanced when we review this repo for local dev.

in my point of view, I am curious about micro shift's impact to us. +@rootfs here.
The logic is:
we have a default development k8s cluster as KIND. and we hope by micro shift, we can cover edge computing related usage. This is something discussed in previously.
I suppose we are going to something like `start $(k8s_cluster_provider)`... but let's wait for @rootfs or @sallyom in https://github.com/sustainable-computing-io/kepler/issues/182

different kind command line version may have different behaviors, and or just mapping to different kind image. @jiere 
for local development, I am open to if there is a kind cluster do nothing... but
I am worried about:
if your local kind with a version less that 0.17.0, with a legacy kind image to set up your k8s cluster, and which fails on CI. as CI use a higher version.

and yes, there is another option we set kind with image version, which will force a kind image during start up.... but, honestly,  there is still some kind of mismatch between version of kind binary and kind image.

+ @jiere , @rootfs , @marceloamaral , @jichenjc here for an open item.
do you think we should use this repo for verify kepler among different hardware?
I am open to discussion but currently I am not optimistic.
- drawback
Let's just use kind as an example for k8s provider.
1st limitation, as @jiere mentioned is kind's limitation on platform as ppc64le.
2nd limitation, different operator system as windows.
3rd limitation, maybe optional , or for .... some edge case, as kepler have to mount host path as kernel and cgroup, even if on linux, maybe the path to those folder may different when we started linux through VM? 
> if you run `uname -a` on default github action agent, you can see the linux header is github specific....
With drawbacks above, which means we can's use this repo to cover all the case in real world, and KIND is not a product ready K8S? which means even if we try to use this repo to set up a K8S for verify kepler with hardware, we should not use KIND. 
> kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.

- advantage
as 80/20 rule, if this repo able to cover 80% case, it's worth to do.

**Comment by SamYuan1990** [comment]
Close this issue as no further comments or discussion for now. please free to reopen with comments.

**Comment by marceloamaral** [comment]
@jiere does k3s has the same issues you mentioned before as the kind cluster?
The answer of this will be related to the issue https://github.com/sustainable-computing-io/local-dev-cluster/issues/22

**Comment by jiere** [comment]
Sorry @marceloamaral , I haven't tried k3s yet, will keep an eye on it later.
