### ISSUE TITLE
Add k3s support

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/local-dev-cluster#22]
ref https://github.com/sustainable-computing-io/kepler/pull/313/files#diff-6ea863e2e18d005875add7b7a4d98360c4f3e2a20378916a24bcd4c37c19680f to add k3s support

**Comment by marceloamaral** [comment]
It should be nice to describe the differences between Kind and k3s.

**Comment by SamYuan1990** [comment]
> It should be nice to describe the differences between Kind and k3s.

ref to https://github.com/k3s-io/k3s/releases/tag/v1.27.3%2Bk3s1
it seems k3s has better support on s390x than kind(https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0).

**Comment by SamYuan1990** [comment]
in general, we just depends on k8s api, hence any k8s certified cluster works for us.

**Comment by SamYuan1990** [comment]
hence I am open to have this ticket in our scope or not.

**Comment by marceloamaral** [comment]
I think we don't need to enable it in CI.
But we can support it to create local cluster for development purpose.

**Comment by SamYuan1990** [comment]
close for now.
