### ISSUE TITLE
add test case for local reg usage

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/local-dev-cluster#23]
ref https://github.com/sustainable-computing-io/local-dev-cluster/pull/20#issuecomment-1611326486

my plan is to tag nginx image at local to lcoalhost:5000/nginx some thing.
and deploy a nginx on k8s cluster created locally for test.

**Comment by vprashar2929** [comment]
@SamYuan1990 I think we can close this as [changes](https://github.com/sustainable-computing-io/local-dev-cluster/pull/24) got merged
