### ISSUE TITLE
Cleanup kind fetch related code.

### ISSUE THREAD

**Issue by jiere** [sustainable-computing-io/local-dev-cluster#26]
Just noticed [here](https://github.com/actions/runner-images/tree/main/images/linux) for Github-hosted runners supported image/tool list. `Kind` is already there for both `Ubuntu 20.04` and `Ubuntu 22.04` runners with both latest `0.20.0` version.
So I would prefer to clean up current fetch kind related codes and directly call kind command in our scripts.

**Comment by marceloamaral** [comment]
@jiere can you please provide more details of this idea?

Note that, we must have the scripts to also create similar environment locally (server or laptop) for development purposes.

**Comment by jiere** [comment]
@marceloamaral , currently kepler's GHA runs on Github-hosted runners, in various of current workflow yaml files, I found that the runners are either `ubuntu-20.04` or `ubuntu-latest`, the pre-installed package list of these two type of runners are in https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md and https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md.

The workflow yamls are used for GHA, so we do not need to install redundant tools/packages if they are already installed on those runners. For Kepler's case, `kind` and `kubectl` are both no need to be installed.

Due to your mentioned similar local dev environment setup purpose, yes, both `kind` and `kubectl` are needed to be installed, but we do not need to write yamls or GHA node.js code to do so, just mention them in document to remind developers that those are prerequisite packages.

**Comment by sthaha** [comment]
> just mention them in document to remind developers that those are prerequisite packages. Developers could follow related official guides to install them then.

That IMHO doesn't work :-) 

I actually prefer the current approach which validates if the version of the tools are as expected. 

A work around we use in ObO is to provide a make target - https://github.com/rhobs/observability-operator/blob/9b663b73963cf94a91b784680eb5b0cf4aa7c41a/Makefile.tools#L209  

Thus any script can validate the version of the tools and if that fails ask user to run `make tools` and bail out
E.g. https://github.com/rhobs/observability-operator/blob/9b663b73963cf94a91b784680eb5b0cf4aa7c41a/hack/kind/setup.sh#L62
