### ISSUE TITLE
Bump up local-dev-cluster version

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/local-dev-cluster#27]
Since we added support for Microshift to local-dev-cluster repo. In order for Kepler repo and Kepler-Operator repo's CI to work it would be best to have a bump up in the version.

CC: @rootfs @SamYuan1990

**Comment by SamYuan1990** [comment]
closed this issue via https://github.com/sustainable-computing-io/local-dev-cluster/tree/v0.0.1

**Comment by vprashar2929** [comment]
Thanks @SamYuan1990 🙂
