### ISSUE TITLE
export kubeconfig to tmp folder

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/local-dev-cluster#29]
export kubeconfig to tmp folder
to avoid export kubeconfig in kepler and kepler operator repos, to reduce copy paste code parts.

**Comment by sthaha** [comment]
@SamYuan1990 can we close this? With #31 merged, the default ~/.kube/config will be overwritten if the cluster could be setup properly. The path can be overridden by setting CLUSTER_KUBECONFIG to any path

**Comment by SamYuan1990** [comment]
LGTM close for now.
