### ISSUE TITLE
Refactor setup code to be  more maintainable by reducing side-effects and globals

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/local-dev-cluster#30]
Since the idea is to support multiple k8s flavours it would be great if we can structure the code in way that reduces side effects of `sourcing` a bash library. E.g. 

In the current code, we load both kind and microshift libraries when only one is  required. The sideffects of loading kind overflows into microshift. E.g. `_output/generated-manifest` etc. 

The way I see this, we have 3 groups of bash related functions 
1. common bootup script (main functions) that is generic across all clusters 
2. common k8s utilties
3. cluster specific functions

**Comment by sthaha** [comment]
I have a draft PR that implements the above. Note, its a draft and is created to gather feedback. I am happy to work with `minishift` maintainers (may worth adding a MAINTAINER file) to refactor that as well.

**Comment by SamYuan1990** [comment]
I suppose there are two discussion in this issue one is code refactor and another is:
do we need support `minishift` ? as we have microshift and kind already? @rootfs, wdyt?

**Comment by SamYuan1990** [comment]
I am not sure if CNCF should make an repo to all people to create a k8s cluster from any of k8s provider by their preferred ? @rootfs

**Comment by vprashar2929** [comment]
I think what @sthaha wanted to mention is `microshift` instead of `minishift`. @sthaha Correct me if I am wrong

**Comment by sthaha** [comment]
Sorry, my bad, @SamYuan1990 , what I meant was microshift (corrected now). 
Thanks @vprashar2929 for pointing out 🙇

**Comment by sthaha** [comment]
@SamYuan1990 I am going to close this as completely by #31 .
