### ISSUE TITLE
Add validations in CI to ensure PROMETHEUS_ENABLE and GRAFANA_ENABLE are respected

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/local-dev-cluster#42]
Current CI validation did let https://github.com/sustainable-computing-io/local-dev-cluster/pull/41#discussion_r1275647161 slip through the cracks and it can happen in future unless we validate that these flags are actually respected.

**Comment by SamYuan1990** [comment]
can we close this ticket?
