### ISSUE TITLE
add wait for tekton deployment to finish

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/local-dev-cluster#95]
Ref: https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/11572919947/job/32214031737

temporary address: https://github.com/sustainable-computing-io/kepler-model-server/pull/540

**Comment by SamYuan1990** [comment]
@vprashar2929 , could you please create a PR at local dev cluster repo?
we impl tekton deployment logic at https://github.com/sustainable-computing-io/local-dev-cluster/blob/main/main.sh#L53

**Comment by vprashar2929** [comment]
yes will do

**Comment by vprashar2929** [comment]
closing as #96 addresses this
